services:
  ldap-util-app:
    image: inyourhead/ldap-util-app:3.4.1
    environment:
      - 'ACTIVE_PROFILES'
    ports:
      - "8080:8080"
    healthcheck:
      test: curl -m 5 --silent --fail --request GET http://localhost:8080/actuator/health | jq --exit-status -n 'inputs | if has("status") then .status=="UP" else false end' > /dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 10