version: "3"
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: ldap-util-openldap
    restart: no
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=TestAdminPassword1234!
      - LDAP_USERS=joe,daisy,tom
      - LDAP_USER_DC=users
      - LDAP_GROUP=readers
      - LDAP_PASSWORDS=joePassword1!,daisyPassword2!,tomPassword3!
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP_ENABLE_ACCESSLOG=true
    ports:
      - "1389:1389"